version: '3'

volumes:
{%- if cookiecutter.cloud_provider == 'None' %}
  django_media: {}
{%- endif %}
  postgres_data: {}
  postgres_data_backups: {}
  traefik: {}
{%- if cookiecutter.use_elasticsearch == 'y' %}
  elasticsearch_data: {}
{%- endif %}

services:
  django:{% if cookiecutter.use_celery == 'y' %} &django{% endif %}
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: {{ cookiecutter.project_slug }}_liv_django
    {%- if cookiecutter.cloud_provider == 'None' %}
    volumes:
      - django_media:/app/{{ cookiecutter.project_slug }}/media
    {%- endif %}
    depends_on:
      - postgres
      - redis
      {%- if cookiecutter.use_elasticsearch == 'y' %}
      - elasticsearch
      {%- endif %}
    env_file:
      - ./.envs/.liv/.django
      - ./.envs/.liv/.postgres
    command: /start

  {%- if cookiecutter.cloud_provider == 'None' %}
  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: {{ cookiecutter.project_slug }}_liv_nginx
    depends_on:
      - django
    volumes:
      - django_media:/usr/share/nginx/media:ro
  {%- endif %}

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: {{ cookiecutter.project_slug }}_liv_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - ./.envs/.liv/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/kdl/traefik/Dockerfile
    image: {{ cookiecutter.project_slug }}_liv_traefik
    depends_on:
      - django
    volumes:
      - traefik:/etc/traefik/acme
    ports:
      - '127.0.0.1:8201:80'

  redis:
    image: redis:5.0
  {%- if cookiecutter.use_celery == 'y' %}

  celeryworker:
    <<: *django
    image: {{ cookiecutter.project_slug }}_liv_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: {{ cookiecutter.project_slug }}_liv_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: {{ cookiecutter.project_slug }}_liv_flower
    ports:
      - "5555:5555"
    command: /start-flower

  {%- endif %}

  {% if cookiecutter.cloud_provider == 'AWS' %}
  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    env_file:
      - ./.envs/.liv/.django
    volumes:
      - postgres_data_backups:/backups
  {%- endif %}
  {%- if cookiecutter.use_elasticsearch == 'y' %}

  elasticsearch:
    image: elasticsearch:7.5.1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    env_file:
      - ./.envs/.liv/.elasticsearch
    ports:
      - '127.0.0.1:9200:9200'
      - '127.0.0.1:9300:9300'

    kibana:
      image: kibana:7.5.1
      depends_on:
        - elasticsearch
      env_file:
        - ./.envs/.liv/.kibana
      ports:
        - '5601:5601'

  {%- endif %}
