image: ubuntu:latest

services:
  - docker:stable-dind

before_script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip libffi-dev libssl-dev gcc libc-dev make
  - pip install -U pip
  - pip install docker-compose tox
  - docker-compose -v
  - docker -v

stages:
  - test

py37:
  stage: test
  script: tox -e py37

flake8:
  stage: test
  script: tox -e flake8

black:
  stage: test
  script: tox -e black

black template:
  stage: test
  script: tox -e black-template

basic docker:
  stage: test
  script: sh tests/test_docker.sh

docker with celery:
  stage: test
  script: sh tests/test_docker.sh use_celery=y

bare metal:
  stage: test
  script: sh tests/test_bare.sh use_celery=y use_compressor=y
  services:
    - postgres
    - redis
  variables:
    CELERY_BROKER_URL: redis://localhost:6379/0
