default:
  image: python:3.7-slim
  services:
    - docker:dind
  before_script:
    - pip install tox

stages:
  - test

black:
  stage: test
  script: tox -e black

black template:
  stage: test
  script: tox -e black-template

flake8:
  stage: test
  script: tox -e flake8

py37:
  stage: test
  script: tox -e py37

basic docker:
  stage: test
  script: sh tests/test_docker.sh

docker with celery:
  stage: test
  script: sh tests/test_docker.sh use_celery=y

bare metal:
  stage: test
  services:
    - postgres
    - redis
  variables:
    CELERY_BROKER_URL: redis://localhost:6379/0
  script:
    - apt-get update
    # dependencies for building Python packages
    - apt-get install -y build-essential
    # psycopg2 dependencies
    - apt-get install -y libpq-dev
    # Translations dependencies
    - apt-get install -y gettext
    - sh tests/test_bare.sh use_celery=y use_compressor=y
