default:
  image: python:3.8
  before_script:
    - apt-get update
    # dependencies for building Python packages
    - apt-get install -y build-essential
    # psycopg2 dependencies
    - apt-get install -y libpq-dev
    # Translations dependencies
    - apt-get install -y gettext
    - pip install docker-compose
    - pip install tox

stages:
  - lint
  - test

black:
  stage: lint
  script: tox -e black-template

py38:
  stage: test
  script: tox -e py38

basic docker:
  image: docker/compose:latest
  stage: test
  services:
    - docker:dind
  script: sh tests/test_docker.sh

docker with celery:
  image: docker/compose:latest
  stage: test
  services:
    - docker:dind
  script: sh tests/test_docker.sh use_celery=y use_drf=y

bare metal:
  stage: test
  services:
    - postgres
    - redis
  variables:
    CELERY_BROKER_URL: redis://localhost:6379/0
    POSTGRES_USER: 'my_awesome_project'
    POSTGRES_PASSWORD: ''
    POSTGRES_DB: 'test_my_awesome_project'
    POSTGRES_HOST_AUTH_METHOD: trust
    DATABASE_URL: pgsql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB
  script:
    - echo $DATABASE_URL
    - sh tests/test_bare.sh use_celery=y use_compressor=y
