log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"

http:
  routers:
    web-router:
      rule: "Host(`{{ cookiecutter.project_slug }}-stg.kdl.kcl.ac.uk`)"
      entryPoints:
        - web
      middlewares:
        - csrf
      service: django

    {%- if cookiecutter.cloud_provider == 'None' %}

    web-media-router:
      rule: "Host(`{{ cookiecutter.project_slug }}-stg.kdl.kcl.ac.uk`) && PathPrefix(`/media/`)"
      entryPoints:
        - web
      middlewares:
        - csrf
      service: django-media
    {%- endif %}

  middlewares:
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ['X-CSRFToken']

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    {%- if cookiecutter.cloud_provider == 'None' %}
    django-media:
      loadBalancer:
        servers:
          - url: http://nginx:80
    {%- endif %}

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
